[env:seeed_xiao_nrf52840_sense]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840
framework = arduino

; Libraries
lib_deps =
    adafruit/Adafruit SHT4x Library
    claws/BH1750
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit SPIFlash@>=4.0.0

; Monitor settings
monitor_speed = 115200